---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  yum_repository:
    name: Red Hat Enterprise Linux 7
    description: Red Hat Enterprise Linux 7
    baseurl: http://192.168.0.5/repos/rhel-7-server-rpms
    enabled: yes
    gpgcheck: no

- name: Red Hat Enterprise Linux 7 Common
  yum_repository:
    name: Red Hat Enterprise Linux 7 Common
    description: Red Hat Enterprise Linux 7 Common
    baseurl: http://192.168.0.5/repos/rhel-7-server-rh-common-rpms
    enabled: yes
    gpgcheck: no

- name: Red Hat Enterprise Linux 7 Extras
  yum_repository:
    name: Red Hat Enterprise Linux 7 Extras
    description: Red Hat Enterprise Linux 7 Extras
    baseurl: http://192.168.0.5/repos/rhel-7-server-extras-rpms
    enabled: yes
    gpgcheck: no

- name: Red Hat Enterprise Linux 7 Optional
  yum_repository:
    name: Red Hat Enterprise Linux 7 Optional
    description: Red Hat Enterprise Linux 7 Optional
    baseurl: http://192.168.0.5/repos/rhel-7-server-optional-rpms
    enabled: yes
    gpgcheck: no


 
- name: install base tools and packages
  yum:
    name:
      - Development Tools
      - net-tools
    state: present
 
